Fix vm listing traceback and manpage strings
Traceback (most recent call last):
  File "/usr/bin/resalloc-ibm-cloud-list-vms", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/resalloc_ibm_cloud/ibm_cloud_list_vms.py", line 18, in main
    pool_id = opts.pool or os.getenv("RESALLOC_POOL_ID")
              ^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'pool'

The manpages contained `argparsers.py` string, instead of the utility
name, therefore defining prog= now.